### ISSUE TITLE
TypeError ('levels' for metric must be a 2-tuple or None) with checkmk version 2.1.0p24

### ISSUE THREAD

**Issue by kiessl93** [bashclub/checkmk-smart#1]
Hello,

got this issue:

![2023-03-31 13_37_25-Checkmk Local site monitoring - Crash report_ 25f7958c-cfb6-11ed-81c5-e6c04d46d9](https://user-images.githubusercontent.com/129511592/229110717-7bb064b3-c30d-4d8c-9273-2425871cdbef.png)

**Comment by rowie** [comment]
OMD[rowie]:~$ mkp install disk_smart_info-0.6-2.mkp 
Traceback (most recent call last):
  File "/omd/sites/rowie/lib/python3.9/tarfile.py", line 1691, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/omd/sites/rowie/lib/python3.9/tarfile.py", line 1668, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/omd/sites/rowie/lib/python3.9/tarfile.py", line 1531, in __init__
    self.firstmember = self.next()
  File "/omd/sites/rowie/lib/python3.9/tarfile.py", line 2363, in next
    raise e
  File "/omd/sites/rowie/lib/python3.9/tarfile.py", line 2336, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/omd/sites/rowie/lib/python3.9/tarfile.py", line 1121, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/omd/sites/rowie/lib/python3.9/gzip.py", line 300, in read
    return self._buffer.read(size)
  File "/omd/sites/rowie/lib/python3.9/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/omd/sites/rowie/lib/python3.9/gzip.py", line 487, in read
    if not self._read_gzip_header():
  File "/omd/sites/rowie/lib/python3.9/gzip.py", line 435, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b'40')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/omd/sites/rowie/bin/check_mk", line 92, in <module>
    exit_status = modes.call(mode_name, mode_args, opts, args)
  File "/omd/sites/rowie/lib/python3/cmk/base/modes/__init__.py", line 69, in call
    return handler(*handler_args)
  File "/omd/sites/rowie/lib/python3/cmk/base/modes/check_mk.py", line 742, in mode_packaging
    cmk.base.packaging.do_packaging(args)
  File "/omd/sites/rowie/lib/python3/cmk/base/packaging.py", line 95, in do_packaging
    f(args)
  File "/omd/sites/rowie/lib/python3/cmk/base/packaging.py", line 327, in package_install
    package = packaging.store_package(fh.read())
  File "/omd/sites/rowie/lib/python3/cmk/utils/packaging.py", line 330, in store_package
    with tarfile.open(fileobj=BytesIO(file_content), mode="r:gz") as tar:
  File "/omd/sites/rowie/lib/python3.9/tarfile.py", line 1638, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/omd/sites/rowie/lib/python3.9/tarfile.py", line 1695, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file
